# -*- coding: utf-8 -*-

import names


def main():
    startApplication("PM.TruckFlow.Clients.OperatorStation")
    clickButton(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Connexion_Button))
    clickButton(waitForObject(names.licence_requise_Continuer_avec_la_version_d_essai_Button))
    mouseClick(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_System_Windows_Controls_Viewbox_ToggleButton))
    mouseClick(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Badge_TabItem))
    clickButton(waitForObject(names.badge_System_Windows_Controls_Viewbox_Button))
    mouseClick(waitForObject(names.pesage_Code_badge_Edit), 23, 22, MouseButton.PrimaryButton)
    type(waitForObject(names.pesage_Code_badge_Edit), "123")
    type(waitForObject(names.pesage_Code_badge_Edit), "<Tab>")
    type(waitForObject(names.pesage_Libell_badge_Edit), "123")
    mouseClick(waitForObject(names.pesage_Plaque_Label))
    clickButton(waitForObject(names.pesage_System_Windows_Controls_Viewbox_Button))
    type(waitForObject(names.camion_Plaque_Edit), "123")
    clickButton(waitForObject(names.camion_OK_Button))
    clickButton(waitForObject(names.badge_OK_Button))
    mouseClick(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_System_Windows_Controls_Viewbox_ToggleButton_2))
    clickButton(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_System_Windows_Controls_Viewbox_Button))
    mouseClick(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Code_badge_Label))
    mouseClick(waitForObject(names.pART_Popup_123_Label))
    mouseClick(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Code_tiers_Label))
    clickButton(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_System_Windows_Controls_Viewbox_Button_2))
    type(waitForObject(names.tiers_Code_tiers_Edit), "123")
    mouseClick(waitForObject(names.tiers_Libell_tiers_Edit), 91, 11, MouseButton.PrimaryButton)
    type(waitForObject(names.tiers_Libell_tiers_Edit), "123")
    clickButton(waitForObject(names.tiers_OK_Button))
    mouseClick(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Code_produit_Label))
    clickButton(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_System_Windows_Controls_Viewbox_Button_3))
    type(waitForObject(names.produit_Code_produit_Edit), "123")
    type(waitForObject(names.produit_Code_produit_Edit), "<Tab>")
    type(waitForObject(names.produit_Edit), "123")
    clickButton(waitForObject(names.produit_OK_Button))
    expand(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Quantit_ComboBox))
    expand(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Quantit_ComboBox))
    mouseClick(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Edit), 85, 19, MouseButton.PrimaryButton)
    type(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Edit), "500")
    mouseClick(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_WPFControl), 1072, 401, MouseButton.PrimaryButton)
    mouseClick(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Exp_dition_ToggleButton))
    clickButton(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_Capturer_Button))
    clickButton(waitForObject(names.truckflow_par_Precia_Molen_v_1_35_0_System_Windows_Controls_Viewbox_Button_4))
